### ISSUE TITLE
Update-PSResource timeout

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#1060]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Beta 20 `Update-PSResource` times out while updating. In addition to that it does not respond to `CTRL+C`.

```
Update-PSResource -PassThru
Update-PSResource: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

### Expected behavior

```console
# updates modules
```

### Actual behavior

```console
Update-PSResource: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
```

### Error details

```console
Exception             :
    Type              : System.Threading.Tasks.TaskCanceledException
    CancellationToken : System.Threading.CancellationToken
    TargetSite        :
        Name          : HandleFailure
        DeclaringType : System.Net.Http.HttpClient
        MemberType    : Method
        Module        : System.Net.Http.dll
    Message           : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
    InnerException    :
        Type           : System.TimeoutException
        Message        : The operation was canceled.
        InnerException :
            Type              : System.Threading.Tasks.TaskCanceledException
            CancellationToken : System.Threading.CancellationToken
            TargetSite        :
                Name          : MoveNext
                DeclaringType : System.Net.Http.HttpConnection+ContentLengthReadStream+<CompleteCopyToAsync>d__5,
System.Net.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                MemberType    : Method
                Module        : System.Net.Http.dll
            Message           : The operation was canceled.
            InnerException    :
                Type           : System.IO.IOException
                TargetSite     :
                    Name          : ThrowException
                    DeclaringType : System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs, System.Net.Sockets,
Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                    MemberType    : Method
                    Module        : System.Net.Sockets.dll
                Message        : Unable to read data from the transport connection: The I/O operation has been aborted
because of either a thread exit or an application request..
                InnerException :
                    Type            : System.Net.Sockets.SocketException
                    Message         : The I/O operation has been aborted because of either a thread exit or an
application request.
                    SocketErrorCode : OperationAborted
                    ErrorCode       : 995
                    NativeErrorCode : 995
                    HResult         : -2147467259
                Source         : System.Net.Sockets
                HResult        : -2146232800
                StackTrace     :
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken
cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.In
t32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sou
rces.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sou
rces.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32
bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken
cancellationToken)
            Source            : System.Net.Http
            HResult           : -2146233029
            StackTrace        :
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken
cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream,
CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption
completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
CancellationToken originalCancellationToken)
        HResult        : -2146233083
    Source            : System.Net.Http
    HResult           : -2146233029
    StackTrace        :
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response,
CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption
completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
CancellationToken originalCancellationToken)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.V2ServerAPICalls.SendV2RequestForContentAsync(HttpRequestMessage
message, HttpClient s_client)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.V2ServerAPICalls.HttpRequestCallForContent(String requestUrlV2,
ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.V2ServerAPICalls.InstallName(String packageName, Boolean
includePrerelease, ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.HttpInstallPackage(VersionType searchVersionType,
NuGetVersion specificVersion, VersionRange versionRange, String pkgNameToInstall, PSRepositoryInfo repository,
ServerApiCall currentServer, ResponseUtil currentResponseUtil, String tempInstallPath, Hashtable packagesHash,
ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.HttpInstall(String[] pkgNamesToInstall,
PSRepositoryInfo repository, ServerApiCall currentServer, ResponseUtil currentResponseUtil, ScopeType scope, Boolean
skipDependencyCheck, FindHelper findHelper)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.ProcessRepositories(String[] repository, Boolean
trustRepository, Boolean skipDependencyCheck, ScopeType scope)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.InstallPackages(String[] names, VersionRange
versionRange, NuGetVersion nugetVersion, VersionType versionType, String versionString, Boolean prerelease, String[]
repository, Boolean acceptLicense, Boolean quiet, Boolean reinstall, Boolean force, Boolean trustRepository, Boolean
noClobber, Boolean asNupkg, Boolean includeXml, Boolean skipDependencyCheck, Boolean authenticodeCheck, Boolean
savePkg, List`1 pathsToInstallPkg, Nullable`1 scope, String tmpPath, HashSet`1 pkgsInstalled)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Update-PSResource], TaskCanceledException
FullyQualifiedErrorId :
System.Threading.Tasks.TaskCanceledException,Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource
InvocationInfo        :
    MyCommand        : Update-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 4
    Line             : update-psResource -PassThru
    Statement        : update-psResource -PassThru
    PositionMessage  : At line:1 char:1
                       + update-psResource -PassThru
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : update-psResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
7.4-preview2
beta20
```

**Comment by gwojan** [comment]
I have run into the same issue the last few weeks because Comcast is being, ahem, Comcast. 😠  It would be very nice to be able to configure the `HttpClient.Timeout` for the PowerShellGet module to deal with low bandwidth scenarios.

**Comment by SydneyhSmith** [comment]
Thanks, was this with PowerShell Gallery or another repo?

**Comment by ThomasNieto** [comment]
This was using the gallery. My internet wasn't the problem and I believed I checked v2 and it was fine.

**Comment by Darian-FRB** [comment]
I have consistently encountered this error with two modules, below. I am on a throttled VPN connection for work.

Install-PSResource -Name AWSPowerShell.NetCore -Scope CurrentUser
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

Install-PSResource -Name Microsoft.Graph.Beta -Scope CurrentUser
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

**Comment by SydneyhSmith** [comment]
We discussed sending this to 10 minutes httpClient.Timeout = TimeSpan.FromMinutes(10);
