### ISSUE TITLE
Unable to successfully install package <path> already exists

### ISSUE THREAD

**Issue by ngetchell-pi** [PowerShell/PSResourceGet#1189]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

I am a devops engineer, looking to replace a legacy nuget provider with GitHub packages. This would allow us to publish our powershell modules across many scenarios. 

Even when applying a temp path, I get the same issue where there .rels files already exist. The files and folders do not exist, even when I step into each action. 

### Expected behavior

```console
The module installs without issue.
```

### Actual behavior

```console
Find-PSResource -Repository GithubPackagesFeed -Credential $credentials -name <ModuleName> | Install-PSResource -Credential $credentials -Verbose
VERBOSE: All paths to search: 'C:\Users\<username>\Documents\PowerShell\Modules'
VERBOSE: All paths to search: 'C:\Users\<username>\Documents\PowerShell\Scripts'
VERBOSE: Retrieving directories in the path 'C:\Users\<username>\Documents\PowerShell\Modules'
VERBOSE: Retrieving directories in the path 'C:\Users\<username>\Documents\PowerShell\Scripts'
<truncated>
VERBOSE: Performing the operation "Install-PSResource" on target "package to install: '<ModuleName>'".
VERBOSE: Parameters passed in >>> Name: '<ModuleName>'; VersionRange: '1.2.1'; NuGetVersion: '1.2.1'; VersionType: 'SpecificVersion'; Version: ''; Prerelease: 'False'; Repository: 'GithubPackagesFeed'; AcceptLicense: 'False'; Quiet: 'False'; Reinstall: 'False'; TrustRepository: 'False'; NoClobber: 'False'; AsNupkg: 'False'; IncludeXml 'True'; SavePackage 'False'; TemporaryPath ''
VERBOSE: Attempting to search for packages in 'GithubPackagesFeed'
VERBOSE: Checking if untrusted repository should be used

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its Trusted value by
running the Set-PSResourceRepository cmdlet. Are you sure you want to install the PSResource from 'GithubPackagesFeed'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
WARNING: Installing dependencies is not currently supported for V3 server protocol repositories. The package will be installed without installing dependencies.
Install-PSResource: Unable to successfully install package '<ModuleName>': 'The file 'C:\Users\<username>\AppData\Local\Temp\834335c2-a370-4e72-b3b1-9c2939d3e987\<ModuleName>\1.2.1\_rels\.rels' already exists.' to temporary installation path.
VERBOSE: Attempting to delete 'C:\Users\<username>\AppData\Local\Temp\834335c2-a370-4e72-b3b1-9c2939d3e987'
VERBOSE: Successfully deleted 'C:\Users\<username>\AppData\Local\Temp\834335c2-a370-4e72-b3b1-9c2939d3e987'
```

### Error details

```console
Exception             : 
    Type           : System.Management.Automation.PSInvalidOperationException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Unable to successfully install package '<ModuleName>': 'The file 'C:\Users\<Username>\AppData\Local\Temp\c8a1f14f-7685-4a33-8b86-065494257aa0\<ModuleName>\1.2.1\_rels\.rels' already exists.' to temporary installation path.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperation
    Message        : Unable to successfully install package '<ModuleName>': 'The file 'C:\Users\<Username>\AppData\Local\Temp\c8a1f14f-7685-4a33-8b86-065494257aa0\<ModuleName>\1.2.1\_rels\.rels' already exists.' to temporary installation path.
    InnerException : 
        Type       : System.IO.IOException
        TargetSite : 
            Name          : CreateFile
            DeclaringType : Microsoft.Win32.SafeHandles.SafeFileHandle
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Message    : The file 'C:\Users\<Username>\AppData\Local\Temp\c8a1f14f-7685-4a33-8b86-065494257aa0\<ModuleName>\1.2.1\_rels\.rels' already exists.
        Source     : System.Private.CoreLib
        HResult    : -2147024816
        StackTrace : 
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.TryInstallToTempPath(Stream responseStream, String tempInstallPath, String pkgName, String normalizedPkgVersion, PSResourceInfo pkgToInstall, Hashtable packagesHash, Hashtable& updatedPackagesHash, ErrorRecord& error)
    HResult        : -2146233079
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper
CategoryInfo          : InvalidOperation: (Microsoft.PowerShelΓÇªdlets.InstallHelper:InstallHelper) [Install-PSResource], PSInvalidOperationException
FullyQualifiedErrorId : InstallPackageFailure,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
InvocationInfo        : 
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 92
    HistoryId        : 27
    Line             : Find-PSResource -Repository GithubPackagesFeed -Credential $credentials -name <ModuleName> | Install-PSResource -Credential $credentials -Verbose -Debug
    PositionMessage  : At line:1 char:92
                       + ΓÇª ipwshcore | Install-PSResource -Credential $credentials -Verbose -Deb ΓÇª
                       +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : 
```

### Environment data

```powershell
PS C:\Users\<username>\Git> Get-Module Microsoft.PowerShell.PSResourceGet; $PSVersionTable | format-table

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     0.5.22     beta22     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PS…


Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by ngetchell-pi** [comment]
Confirmed in an Ubuntu

``` console
> get-module Microsoft.PowerShell.PSResourceGet; $PSVersionTable | format-table
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     0.5.22     beta22     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}


Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

``` console
> Get-Error
Exception             :
    Type           : System.Management.Automation.PSInvalidOperationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Unable to successfully install package '<modulename>': 'The file '/tmp/d9628699-3d5e-4d6d-b103-e3e9fa49e1cf/<modulename>/1.2.1/_rels/.rels' already exists.' to temporary installation path.
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperation
    Message        : Unable to successfully install package '<modulename>': 'The file '/tmp/d9628699-3d5e-4d6d-b103-e3e9fa49e1cf/<modulename>/1.2.1/_rels/.rels' already exists.' to temporary installation path.
    InnerException :
        Type       : System.IO.IOException
        TargetSite :
            Name          : ThrowExceptionForIoErrno
            DeclaringType : Interop, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Message    : The file '/tmp/d9628699-3d5e-4d6d-b103-e3e9fa49e1cf/<modulename>/1.2.1/_rels/.rels' already exists.
        Source     : System.Private.CoreLib
        HResult    : 17
        StackTrace :
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Fun
c`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileStreamOptions options)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.TryInstallToTempPath(Stream responseStream, String tempInstallPath, String pkgName, String normalizedPkgVersion, PSResourceInfo pkgToInstall, Hashtable packagesHash, Hashtable& updatedPack
agesHash, ErrorRecord& error)
    HResult        : -2146233079
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…dlets.InstallHelper:InstallHelper) [Install-PSResource], PSInvalidOperationException
FullyQualifiedErrorId : InstallPackageFailure,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 94
    HistoryId        : 24
    Line             : find-psresource -Name "<modulename>" -Repository githubpackagesfeed -Credential $credentials | Install-PSResource -Credential $credentials
    PositionMessage  : At line:1 char:94
                       + … Credential $credentials | Install-PSResource -Credential $credentials
                       +                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

**Comment by alerickson** [comment]
@ngetchell-pi is there a module that you could share that we can test against?

**Comment by anamnavi** [comment]
@ngetchell-pi we tried repro'ing this on Ubuntu22 with some test packages and are not able to. If you could provide the name of the module you're testing against we can work to resolve this.
