### ISSUE TITLE
Find-PSResource does not work with UNC paths

### ISSUE THREAD

**Issue by peetrike** [PowerShell/PSResourceGet#1218]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
Register-PSResourceRepository -Name test -Uri \\server\share\folder
Find-PSResource -Type Module -Repository test
```

### Expected behavior

```console
contents of repository or empty results
```

### Actual behavior

```console
Find-PSResource: Could not find a part of the path 'C:\server\share\folder'
```

### Error details

```console
Exception             :
    Type       : System.IO.DirectoryNotFoundException
    TargetSite :
        Name          : CreateDirectoryHandle
        DeclaringType : System.IO.Enumeration.FileSystemEnumerator`1[TResult]
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Could not find a part of the path 'C:\server\share\folder'.
    Source     : System.Private.CoreLib
    HResult    : -2147024893
    StackTrace :
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.LocalServerAPICalls.GetMatchingFilesGivenNamePattern(String packageNameWithWildcard, Boolean includePrerelease)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.LocalServerAPICalls.FindTagsHelper(String[] tags, Boolean includePrerelease, ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.LocalServerAPICalls.FindAll(Boolean includePrerelease, ResourceType type, ExceptionDispatchInfo& edi)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper.SearchByNames(ServerApiCall currentServer, ResponseUtil currentResponseUtil, PSRepositoryInforepository)+MoveNext()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper.FindByResourceName(String[] name, ResourceType type, VersionRange versionRange, NuGetVersion
nugetVersion, VersionType versionType, String version, Boolean prerelease, String[] tag, String[] repository, Boolean includeDependencies)+MoveNext()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource.ProcessResourceNameParameterSet()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Find-PSResource], DirectoryNotFoundException
FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource
InvocationInfo        :
    MyCommand        : Find-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 46
    Line             : find-psresource -Type Script -Repository test
    PositionMessage  : At line:1 char:1
                       + find-psresource -Type Script -Repository test
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : find-psresource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```console
ModuleType Version    PreRelease Name
---------- -------    ---------- ---- 
Binary     0.5.22     beta22     Microsoft.PowerShell.PSResourceGet


Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
Thanks! looks like there is a PR in for this #1229

**Comment by peetrike** [comment]
This problem was caused by comma in ExternalModuleDependencies module list.  The same problem affects also #1243 .

As there is no metadata description for scripts, and PowerShellGet module works with this, the PSReosurceGet could also allow comma as separator between multiple metadata values.

Test-PSScriptFileInfo did not complain about that comma issue.
