### ISSUE TITLE
Null reference exception when installing module internally hosted on Nexus Repository

### ISSUE THREAD

**Issue by variableresistor** [PowerShell/PSResourceGet#1279]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Using Nexus Repository as an internal PowerShell module source.

```powershell
Install-Module -Name Microsoft.PowerShell.PSResourceGet -Repository PSGallery -AllowPrerelease -Scope CurrentUser

Write-Information "Installing secret management stuff using PowerShellGet"
Install-Module -Name Microsoft.PowerShell.SecretManagement,Microsoft.PowerShell.SecretStore -Repository PSGallery -Scope CurrentUser

$Name = "shared-powershell-hosted-dev"
$Location = https://nexus.MyCompany.com/repository/shared-powershell-hosted-dev/
$NexusUserCode = "blah"
$VaultName = "PSRepos"
$Credential = Get-Credential -Message "Enter your Nexus Repo pass code generated from the UI" -UserName $NexusUserCode

Write-Information "Create a new vault for all the PSRepos' secrets"
if (-not (Get-SecretVault | Where-Object -Property Name -eq $VaultName))
{
    Register-SecretVault -Name $VaultName -ModuleName Microsoft.PowerShell.SecretStore
}

Write-Information "Just set the secret to the whole vault to the same password, for simplicity"
Set-SecretStorePassword -NewPassword $Credential.Password -Password $Credential.Password
Unlock-SecretStore -Password $Credential.Password

Write-Information "Create a new secret with the same name as the repository, with type of PSCredential"
Set-Secret -Name $Name -Vault $VaultName -Secret $Credential

Write-Information "Register the package repository"
if (-not (Get-PSResourceRepository | Where-Object -Property Name -EQ $Name))
{
    $Splat = @{
       Name               = $Name
        Uri                   = $Location
        Trusted            = $true
        CredentialInfo = ([Microsoft.PowerShell.PSResourceGet.UtilClasses.PSCredentialInfo]::new($VaultName, $Name))
    }
    Register-PSResourceRepository @Splat
}

Write-Information "Here's where all that scaffolding finally crashes"
Find-PSResource -Name MyCustomModule -Repository $Name
Write-Information "Here's another angle to hit it from"
Install-PSResource -Name MyCustomModule -Repository $Name -Scope CurrentUser
```

I stripped out as much organization-specific information as I could find, so the errors might not exactly line up.

Btw, @SydneyhSmith  I listened to your interview on The PowerShell Podcast, and there's always going to be those people that are rude or say outrageous things. But my experience is that they have their own issues and it's nothing to do with the wonderful work you all are doing here. PowerShellGet v2 was SO slow and my measurements show that this module at least doubled our speed on the build servers. I'd really like to have that compatibility layer you talked about because I see quite a learning curve for new users of PowerShell as far as passing credentials to a repository.

### Expected behavior

```console
It should find/install the module like PowerShellGet v2 does, except without having to pass the -Credential parameter every time. I.e.


Install-Module -Name MyCustomModule -Repository $Name -Credential $Credential


Doesn't use the credential for some reason with this old module if it's registered with that same credential.
```

### Actual behavior

```console
Doesn't do anything but throw an error.
```

### Error details

```console
Exception             :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : MoveNext
        DeclaringType : Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper+<SearchByNames>d__19, Microsoft.PowerShell.PSResourceGet, Version=0.5.22.0, Culture=neutral, PublicKeyToken=null
        MemberType    : Method
        Module        : Microsoft.PowerShell.PSResourceGet.dll
    Message    : Object reference not set to an instance of an object.
    Source     : Microsoft.PowerShell.PSResourceGet
    HResult    : -2147467261
    StackTrace :
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper.SearchByNames(ServerApiCall currentServer, ResponseUtil currentResponseUtil, PSRepositoryInfo repository)+MoveNext()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper.FindByResourceName(String[] name, ResourceType type, VersionRange versionRange, NuGetVersion nugetVersion, VersionType versionType, String  
version, Boolean prerelease, String[] tag, String[] repository, Boolean includeDependencies)+MoveNext()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource.ProcessResourceNameParameterSet()
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Find-PSResource], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource
InvocationInfo        :
    MyCommand        : Find-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 135
    Line             : Find-PSResource -Name MyCustomModule -Repository shared-powershell-hosted-dev
    PositionMessage  : At line:1 char:1
                       + Find-PSResource -Name MyCustomModule -Repository shared-powershell-hosted-dev
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Find-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
and
Exception             :
    Type       : System.ArgumentException
    Message    : Repository shared-powershell-hosted-dev has unknown API Version.
    TargetSite :
        Name          : ThrowTerminatingError
        DeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.3.5.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Source     : System.Management.Automation
    HResult    : -2147024809
    StackTrace :
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…dlets.InstallHelper:InstallHelper) [Install-PSResource], ArgumentException
FullyQualifiedErrorId : RepositoryAPIVersionUnknownError,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 151
    Line             : Install-PSResource -Name MyCustomModule -Repository $Name
    PositionMessage  : At line:1 char:1
                       + Install-PSResource -Name MyCustomModule -Repository $Name
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     0.5.22     beta22     Microsoft.PowerShell.PSResourceGet  Core,Desk {Find-PSResource, Get-InstalledPSResource, Get-PSRes…

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by adityapatwardhan** [comment]
In our next preview release that is expected to be out very shortly, we would have a new parameter for `Set-PSResource Repository` for setting the API version like `-ApiVersion v2`

Could you try using that and report back to us if that helps. 

We have not explicitly tested Nexus repositories, but the above workaround might to the trick if the repository uses the NuGet v2 server protocol.

**Comment by variableresistor** [comment]
> In our next preview release that is expected to be out very shortly, we would have a new parameter for `Set-PSResource Repository` for setting the API version like `-ApiVersion v2`
> 
> Could you try using that and report back to us if that helps.
> 
> We have not explicitly tested Nexus repositories, but the above workaround might to the trick if the repository uses the NuGet v2 server protocol.

Would you like me to try 0.5.22-beta23 (I'm guessing it will be beta23) once it's published, or would you like me to build the project from source? The latter I'm not familiar with, so if you can point me to the docs on how to do that locally I can do that if it helps.

Related to the V2 repository type, I tried registering Chocolatey.org using this:
```powershell
Register-PSResourceRepository -Name Chocolatey.org -Uri https://community.chocolatey.org/api/v2 -Trusted
[version]$Version  = "7.0.9"
$Runtime = "windowshosting"
Find-PSResource -Repository Chocolatey.org -Name "dotnet-$($Version.Major).$($Version.Minor)-$Runtime"
```

`Find-PSResource: Package with search criteria: Name dotnet-7.0-windowshosting could not be found due to: TryConvertFromXml: Cannot parse PSResourceInfo from XmlNode with error: Object reference not set to an instance of an object..`

But I _think_ it's setting the V2 repository correctly because when I run this:
```powershell
Get-PSResourceRepository -Name Chocolatey.org | Select *
```

it yields:
```
Name           : Chocolatey.org
Uri            : https://community.chocolatey.org/api/v2
Trusted        : True
Priority       : 50
CredentialInfo :
ApiVersion     : v2
```

**Comment by anamnavi** [comment]
@variableresistor if you can try beta23 when it releases/is published that would be best. We are aiming to release within the next 48 hours. And then you can register the Nexus repository, use `Set-PSResourceRepository myNexusRepo -ApiVersion v2` and see if it works.

Our fix in this release will write an error message if the repository is not yet supported. It won't throw a null pointer like it currently is. If you change the ApiVersion to v2 it will try that logic.

Over the course of our next releases we will look into explicit support for your Nexus repository. We unfortunately do not support Chocolately at this time, but can look into that as well.

Our current list of supported repositories is: Azure Artifacts, Github Packages, NuGet.org, MyGet.org, JFrog Artifactory, PSGallery, NuGet.Server hosted feeds, and local repositories.

**Comment by anamnavi** [comment]
I'll reply on this issue again when we publish :) Thank you for your feedback, patience and testing!
