### ISSUE TITLE
Update-PSResource fails with Path cannot be null

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSResourceGet#133]
I was trying out `Update-PSResource` in the v3-preview.2 drop and got this error:
```
PS> Update-PSResource Pester -Prerelease -WhatIf
Update-PSResource: Value cannot be null. (Parameter 'path')
```
There is no `Path` parameter on this command so this must be an internal error:
```
Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'path')
    ParamName  : path
    TargetSite :
        Name          : InternalEnumeratePaths
        DeclaringType : System.IO.Directory
        MemberType    : Method
        Module        : System.IO.FileSystem.dll
    StackTrace :
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget,
EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : System.IO.FileSystem
    HResult    : -2147467261
CategoryInfo          : NotSpecified: (:) [Update-PSResource], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource
InvocationInfo        :
    MyCommand        : Update-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 10
    Line             : Update-PSResource Pester -Prerelease -WhatIf
    PositionMessage  : At line:1 char:1
                       + Update-PSResource Pester -Prerelease -WhatIf
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Update-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```
I'm running on Windows 10 1909 w/PS 7.0.0 GA.

**Comment by SydneyhSmith** [comment]
Closing this as resolved
