### ISSUE TITLE
Install-PSResource macOS fails with "Windows Principal functionality is not supported on this platform."

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PSResourceGet#134]
Looks like the code is checking for admin maybe?

```
> Install-PSResource -Name powershell-yaml
Install-PSResource: Windows Principal functionality is not supported on this platform.
```

Output from `Get-Error`:

```
> Get-Error

Exception             :
    Type       : System.PlatformNotSupportedException
    TargetSite :
        Name          : GetCurrent
        DeclaringType : System.Security.Principal.WindowsIdentity
        MemberType    : Method
        Module        : System.Security.Principal.Windows.dll
    StackTrace :
   at System.Security.Principal.WindowsIdentity.GetCurrent()
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord() in /PowerShell/src/System.Management.Automation/engine/cmdlet.cs:line 173
   at System.Management.Automation.CommandProcessor.ProcessRecord() in /PowerShell/src/System.Management.Automation/engine/CommandProcessor.cs:line 388
    Message    : Windows Principal functionality is not supported on this platform.
    Source     : System.Security.Principal.Windows
    HResult    : -2146233031
CategoryInfo          : NotSpecified: (:) [Install-PSResource], PlatformNotSupportedException
FullyQualifiedErrorId : System.PlatformNotSupportedException,Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : Install-PSResource -Name powershell-yaml
    PositionMessage  : At line:1 char:1
                       + Install-PSResource -Name powershell-yaml
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by bgelens** [comment]
@SydneyhSmith at beta6 I'm still unable to test drive due to this issue (also no mention in the beta6 blog post). When is it planned to be resolved so we can give it a try?
