### ISSUE TITLE
Artifactory v2 feed does not work

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#1416]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

If you register a NuGet Artifactory repository it defaults to unknown ApiVersion and if you set it manually to v2 cmdlets will not work.

```powershell
Name           : psgallery-remote
Uri            : https://<server>/api/nuget/powershell-nuget-public-remote
Trusted        : True
Priority       : 50
CredentialInfo :
ApiVersion     : v2


find-pSResource anypackage -Repository psgallery-remote

Name Version Prerelease Repository       Description
---- ------- ---------- ----------       -----------
     0.5.1              psgallery-remote Use various package managers with a single set of commands.

save-PSResource anypackage -Repository psgallery-remote -Path ~
Save-PSResource: Object reference not set to an instance of an object.
```

### Expected behavior

```console
v2 Artifactory feed works
```

### Actual behavior

```console
Various errors like missing package name in find and failing to save.
```

### Error details

```console
Exception             :
    Type       : System.NullReferenceException
    TargetSite :
        Name          : HttpRequestCallForContent
        DeclaringType : Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls,
Microsoft.PowerShell.PSResourceGet, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null
        MemberType    : Method
        Module        : Microsoft.PowerShell.PSResourceGet.dll
    Message    : Object reference not set to an instance of an object.
    Source     : Microsoft.PowerShell.PSResourceGet
    HResult    : -2147467261
    StackTrace :
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.HttpRequestCallForContent(String requestUrlV2,
ErrorRecord& errRecord)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.InstallName(String packageName, Boolean
includePrerelease, ErrorRecord& errRecord)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.InstallPackage(VersionType searchVersionType,
NuGetVersion specificVersion, VersionRange versionRange, String pkgNameToInstall, PSRepositoryInfo repository,
ServerApiCall currentServer, ResponseUtil currentResponseUtil, String tempInstallPath, Hashtable packagesHash,
ErrorRecord& errRecord)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.InstallPackages(String[] pkgNamesToInstall,
PSRepositoryInfo repository, ServerApiCall currentServer, ResponseUtil currentResponseUtil, ScopeType scope, Boolean
skipDependencyCheck, FindHelper findHelper)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.ProcessRepositories(String[] repository, Boolean
trustRepository, Boolean skipDependencyCheck, ScopeType scope)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.BeginInstallPackages(String[] names, VersionRange
versionRange, NuGetVersion nugetVersion, VersionType versionType, String versionString, Boolean prerelease, String[]
repository, Boolean acceptLicense, Boolean quiet, Boolean reinstall, Boolean force, Boolean trustRepository, Boolean
noClobber, Boolean asNupkg, Boolean includeXml, Boolean skipDependencyCheck, Boolean authenticodeCheck, Boolean
savePkg, List`1 pathsToInstallPkg, Nullable`1 scope, String tmpPath, HashSet`1 pkgsInstalled)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource.ProcessSaveHelper(String[] pkgNames, String
pkgVersion, Boolean pkgPrerelease, String[] pkgRepository)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : NotSpecified: (:) [Save-PSResource], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource
InvocationInfo        :
    MyCommand        : Save-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 7
    Line             : save-PSResource anypackage -Repository psgallery-remote -Path ~
    Statement        : save-PSResource anypackage -Repository psgallery-remote -Path ~
    PositionMessage  : At line:1 char:1
                       + save-PSResource anypackage -Repository psgallery-remote -Path ~
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : save-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
7.4-preview5
```

**Comment by ThomasNieto** [comment]
@SydneyhSmith what additional information do you need to reproduce the issue?

**Comment by SydneyhSmith** [comment]
@ThomasNieto thanks for asking you are all good-- I probably shouldn't have used that label, it was just a note to us that we needed to try and repro and I believe @alerickson did repro this, although with a slightly different error message
