### ISSUE TITLE
[v3-beta3] Update-PSResource Failing

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#144]
# PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Error 
```
PS> update-psresource -name pester
Update-PSResource: Value cannot be null. (Parameter 'path')
PS> get-error

Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'path')
    ParamName  : path
    TargetSite :
        Name          : InternalEnumeratePaths
        DeclaringType : System.IO.Directory
        MemberType    : Method
        Module        : System.IO.FileSystem.dll
    StackTrace :
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget,
EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : System.IO.FileSystem
    HResult    : -2147467261
CategoryInfo          : NotSpecified: (:) [Update-PSResource], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.PowerShell.PowerShellGet.Cmdlets.UpdatePSResource
InvocationInfo        :
    MyCommand        : Update-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 17
    Line             : update-psresource -name pester
    PositionMessage  : At line:1 char:1
                       + update-psresource -name pester
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : update-psresource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote looks like a duplicate of https://github.com/PowerShell/PowerShellGet/issues/133

**Comment by JustinGrote** [comment]
Agreed, closing in favor of #133
