### ISSUE TITLE
Find-PSResource fails every time.

### ISSUE THREAD

**Issue by bielawb** [PowerShell/PSResourceGet#148]
I was trying to test PowerShellGet v3, but Find-PSResource fails all the time for me:
```
Find-PSResource -Name PowerShellGet
Find-PSResource : Failed to fetch results from V2 feed at
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&semVerLevel=2.0.0' with following message :
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of
its dependencies. The system cannot find the file specified.
```
It works fine w/o any parameter.

It also works if I specify wildcards.

**Comment by KUTlime** [comment]
#122 probably related.

**Comment by alerickson** [comment]
Hi @bielawb can you try running
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
and let me know if you get the same error?

**Comment by OraDotNetDev** [comment]
> Hi @bielawb can you try running
> `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
> and let me know if you get the same error?

I still get the same error after explicitly setting TLS 1.2

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by OraDotNetDev** [comment]
I can also reproduce this. There's a similar error for Install-PSResource. See below for more details

> Hi @bielawb can you try running
> `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
> and let me know if you get the same error?

I still get the same error after explicitly setting TLS 1.2

<details>
  <summary>Exception details</summary>

  ```
>  Get-InstalledModule PowerShellGet, PackageManagement |
       Select-Object -Property version, name, repository, InstalledLocation

Version     Name              Repository InstalledLocation
-------     ----              ---------- -----------------
3.0.0-beta4 PowerShellGet     PSGallery  C:\Users\adUser\Documents\WindowsPowerShell\Modules\PowerShellGet\3.0.0
1.4.7       PackageManagement PSGallery  C:\Users\adUser\Documents\WindowsPowerShell\Modules\PackageManagement\1.4.7



> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Find-PSResource Microsoft.PowerShell.GraphicalTools -Version *

> $error[0].Exception | select *


Message        : Failed to fetch results from V2 feed at 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Microsoft.PowerShell.GraphicalTools'&semVerLevel=2.0.0' with following message : Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, 
                 PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
Data           : {}
InnerException : System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
                 File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
                    at NuGet.Protocol.HttpStreamValidation.ValidateXml(String uri, Stream stream)
                    at NuGet.Protocol.HttpCacheUtility.<CreateCacheFileAsync>d__2.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at NuGet.Protocol.HttpSource.<>c__DisplayClass14_0`1.<<GetAsync>b__0>d.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__3`1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__3`1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at NuGet.Protocol.HttpSource.<GetAsync>d__14`1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at NuGet.Protocol.V2FeedParser.<LoadXmlAsync>d__52.MoveNext()
                 
                 WRN: Assembly binding logging is turned OFF.
                 To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
                 Note: There is some performance penalty associated with assembly bind failure logging.
                 To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
                 
TargetSite     : Void MoveNext()
StackTrace     :    at NuGet.Protocol.V2FeedParser.<LoadXmlAsync>d__52.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at NuGet.Protocol.V2FeedParser.<QueryV2FeedAsync>d__50.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at NuGet.Protocol.V2FeedParser.<FindPackagesByIdAsync>d__39.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at NuGet.Protocol.PackageMetadataResourceV2Feed.<GetMetadataAsync>d__4.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.PowerShell.PowerShellGet.Cmdlets.FindPSResource.FindPackagesFromSourceHelper(String repositoryUrl, String name, PackageSearchResource pkgSearchResource, PackageMetadataResource pkgMetadataResource, SearchFilter searchFilter, SourceCacheContext srcContext)
                    at Microsoft.PowerShell.PowerShellGet.Cmdlets.FindPSResource.FindPackagesFromSource(String repositoryUrl, CancellationToken cancellationToken)
                    at Microsoft.PowerShell.PowerShellGet.Cmdlets.FindPSResource.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink       : 
Source         : NuGet.Protocol
HResult        : -2146233088

> Install-PSResource -Name Microsoft.PowerShell.GraphicalTools  -Repository PSGallery
Install-PSResource : Could not load file or assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Install-PSResource -Name Microsoft.PowerShell.GraphicalTools  -Reposi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-PSResource], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource

> $error[0].Exception | select *


Message        : Could not load file or assembly 'System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
FileName       : System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
FusionLog      : WRN: Assembly binding logging is turned OFF.
                 To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
                 Note: There is some performance penalty associated with assembly bind failure logging.
                 To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Data           : {}
InnerException :
TargetSite     : Void ProcessRecord()
StackTrace     :    at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink       :
Source         : PowerShellGet
HResult        : -2147024894
  ```
</details>

**Comment by Ayanmullick** [comment]
I'm facing a similar issue.

<details>

<summary>ScreenClip</summary>

![PSGet](https://user-images.githubusercontent.com/17693249/85935803-2f95dd80-b8ba-11ea-87e3-30cdc446c212.gif)

</details>

**Comment by SydneyhSmith** [comment]
Are you still seeing this in the latest version of the module? This should be resolved as of preview 6
