### ISSUE TITLE
Artifactory+NuGet v2: Save/Install broken for prereleases due to incorrect URL

### ISSUE THREAD

**Issue by sean-r-williams** [PowerShell/PSResourceGet#1680]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

1. Configure Artifactory with PowerShell-flavored NuGet feed
2. Publish prerelease package to NuGet (in this case, version `0.9.1-rc01`)
3. Call `Install-PSResource` or `Save-PSResource` with the `-Prerelease` flag

### Expected behavior

```console
PS> Save-PSResource -Name Foo -Path .\modules\ -Prerelease
PS> # completes successfully
```

### Actual behavior

```console
Save-PSResource: 'Response status code does not indicate success: 404.' Request sent: 'https://artifactory.f.q.d.n/artifactory/api/nuget/v2/psgallery-nuget-virtual/Download/Foo/0.9.1'
```

### Error details

```console
PS> Get-Error
Exception             : 
    Type       : Microsoft.PowerShell.PSResourceGet.UtilClasses.ResourceNotFoundException
    TargetSite : 
        Name          : InstallPackages
        DeclaringType : [Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper]
        MemberType    : Method
        Module        : Microsoft.PowerShell.PSResourceGet.dll
    Message    : 'Response status code does not indicate success: 404.' Request sent: 'https://artifactory.f.q.d.n/artifactory/api/nuget/v2/psgallery-nuget-virtual/Download/Foo/0.9.1'
    Source     : Microsoft.PowerShell.PSResourceGet
    HResult    : -2146233088
    StackTrace : 
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.InstallPackages(String[] pkgNamesToInstall, PSRepositoryInfo repository, ServerApiCall currentServer, ResponseUtil currentResponseUtil, ScopeType scope, Boolean skipDependencyCheck,     
FindHelper findHelper)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.ProcessRepositories(String[] repository, Boolean trustRepository, Boolean skipDependencyCheck, ScopeType scope)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.BeginInstallPackages(String[] names, VersionRange versionRange, NuGetVersion nugetVersion, VersionType versionType, String versionString, Boolean prerelease, String[] repository,        
Boolean acceptLicense, Boolean quiet, Boolean reinstall, Boolean force, Boolean trustRepository, Boolean noClobber, Boolean asNupkg, Boolean includeXml, Boolean skipDependencyCheck, Boolean authenticodeCheck, Boolean savePkg, List`1
pathsToInstallPkg, Nullable`1 scope, String tmpPath, HashSet`1 pkgsInstalled)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource.ProcessSaveHelper(String[] pkgNames, String pkgVersion, Boolean pkgPrerelease, String[] pkgRepository)
   at Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…lets.SavePSResource:SavePSResource) [Save-PSResource], ResourceNotFoundException
FullyQualifiedErrorId : InstallPackageFailure,Microsoft.PowerShell.PSResourceGet.Cmdlets.SavePSResource
InvocationInfo        : 
    MyCommand        : Save-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 3
    Line             : Save-PSResource -Name Foo -Path .\modules\ -Prerelease -Debug
    Statement        : Save-PSResource -Name Foo -Path .\modules\ -Prerelease -Debug
    PositionMessage  : At line:1 char:1
                       + Save-PSResource -Name Foo -Path .\modules\ -Prerelease -Debug 
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Save-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : 
      0
      1
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.5                 Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}


Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

The problem here appears to be that PSResourceGet is synthesizing the download URL incorrectly.

Two separate issues:
* `V2ServerAPICalls::InstallVersion()` is making assumptions about the download URL, even though NuGet v2 responses include the download URL in the `<content>` element under the `<entry>` node for a given search result. 
  I've only validated this on PSGallery and Artifactory - not sure if there's historical context for not simply passing the URL from NuGet into functions like `Install*()`. The calling convention of InstallVersion() seems to suggest it was designed to support being called without a preceding `FindPackagesById()` call but I don't think that's actually the case in any scenario.
* For reasons not entirely clear to me at the moment, `InstallVersion` is getting passed the version string without prerelease suffix. My suspicion is that this is due to JFrog not including `NormalizedVersion` properties on returned packages (and thus PSResourceGet backfills a separate version string), but I'm not 100% sure. JFrog is returning the correct version string in all relevant parts of its response, so this is likely something within PSRG.

**Comment by sean-r-williams** [comment]
I _think_ the problem lies somewhere around here:
https://github.com/PowerShell/PSResourceGet/blob/c4097b0196996f2538122bcb2401aaf567b075e5/src/code/InstallHelper.cs#L804-L807

L804 populates `pkgVersion` with `AdditionalMetadata[NormalizedVersion]`. AIUI, this is spec'd to include prerelease strings.

If that property does not exist, we backfill it with `.Version` in L806, which does not include prerelease strings.

I'd posit that this might be broken on any NuGet feed platform which doesn't include `NormalizedVersion` on package responses.
