### ISSUE TITLE
Beta9: Join Error with Install-PSResource

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#231]
```
install-psresource -name psreadline
Install-PSResource: Value cannot be null. (Parameter 'value')
```

### Get-Error
```
Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'value')
    ParamName  : value
    TargetSite :
        Name          : Join
        DeclaringType : string
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.String.Join(String separator, String[] value)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.ProcessInstallParams(String[] _name, String _version,
Boolean _prerelease, String[] _repository, String _scope, Boolean _acceptLicense, Boolean _quiet, Boolean _reinstall,
Boolean _force, Boolean _trustRepository, Boolean _noClobber, PSCredential _credential, String _requiredResourceFile,
String _requiredResourceJson, Hashtable _requiredResourceHash)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : System.Private.CoreLib
    HResult    : -2147467261
CategoryInfo          : NotSpecified: (:) [Install-PSResource], ArgumentNullException
FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 11
    Line             : install-psresource -name psreadline
    PositionMessage  : At line:1 char:1
                       + install-psresource -name psreadline
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : install-psresource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

````
$psversiontable

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote this is a known bug and will be fixed in the next release

**Comment by alerickson** [comment]
Resolved in [beta10](Apparently there is a step in the import process where assemblies are now attempted to remove on load).  Please let us know if you're still encountering this bug.
