### ISSUE TITLE
Get-PSResource fails without path parameter

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#265]
Get-PSResource throws an error on beta10 when running without a `-Path` parameter.

```powershell
C:\> Get-PSResource
Get-PSResource: The path is empty. (Parameter 'path')
C:\> Get-Error

Exception             :
    Type       : System.ArgumentException
    Message    : The path is empty. (Parameter 'path')
    ParamName  : path
    TargetSite :
        Name          : GetFullPath
        DeclaringType : System.IO.Path
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    StackTrace :
   at System.IO.Path.GetFullPath(String path)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions
options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions
options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression,
EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget,
EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.GetHelper.ProcessGetParams(String[] name, String version, Boolean
prerelease, String path)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.GetPSResource.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : System.Private.CoreLib
    HResult    : -2147024809
CategoryInfo          : NotSpecified: (:) [Get-PSResource], ArgumentException
FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.PowerShellGet.Cmdlets.GetPSResource
InvocationInfo        :
    MyCommand        : Get-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Get-PSResource
    PositionMessage  : At line:1 char:1
                       + Get-PSResource
                       + ~~~~~~~~~~~~~~
    InvocationName   : Get-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by SydneyhSmith** [comment]
Thanks @ThomasNieto this should be resolved in our next release, but we will also add some verbose logging here to better diagnose if this is still occurring

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
