### ISSUE TITLE
Install-Module does not find module if custom VSTS repo registered

### ISSUE THREAD

**Issue by VerdonTrigance** [PowerShell/PSResourceGet#46]
I have 3 PSRepositories. PSGallery, VSTS, Nuget on-prem.
I want to install Pester module

## Expected Behavior
Install-module 'Pester' should find modules in every psrepostory and then install it.

## Current Behavior

```
PS C:\Users\t> Install-Module Pester -Proxy 'http://proxy:8080' -ProxyCredential $Cred -Debug
DEBUG: 00:00:00.0000021 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0001529 Debug: True
DEBUG: 00:00:00.0002408 ProxyCredential: System.Management.Automation.PSCredential
DEBUG: 00:00:00.0002963 Proxy: http://proxy:8080/
DEBUG: 00:00:00.0003305 Name: Pester
DEBUG: 00:00:00.0017832 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0033804 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0257777 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0341868 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0342435 Debug: True
DEBUG: 00:00:00.0342776 ProxyCredential: System.Management.Automation.PSCredential
DEBUG: 00:00:00.0343102 Proxy: http://proxy:8080/
DEBUG: 00:00:00.0343417 Name: Pester
DEBUG: 00:00:00.0356674 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0370115 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0416523 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0487684 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0488213 Debug: True
DEBUG: 00:00:00.0488517 ProxyCredential: System.Management.Automation.PSCredential
DEBUG: 00:00:00.0488517 Proxy: http://proxy:8080/
DEBUG: 00:00:00.0489182 Name: Pester
DEBUG: 00:00:00.0500623 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0514817 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0626423 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0785724 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0786264 Debug: True
DEBUG: 00:00:00.0786595 ProxyCredential: System.Management.Automation.PSCredential
DEBUG: 00:00:00.0786917 Proxy: http://proxy:8080/
DEBUG: 00:00:00.0787225 Name: Pester
DEBUG: 00:00:00.0798822 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0811992 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0885465 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:02.2381372 Calling SearchForPackages. Name='Pester'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:02.2404415 PackageProvider::FindPackage with name Pester
DEBUG: 00:00:02.2409007 Calling SearchForPackages After Select 1
DEBUG: 00:00:02.8408548 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:02.8423451 ProviderName: PowerShellGet
DEBUG: 00:00:02.8442593 Type: Module
DEBUG: 00:00:02.8639346 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:02.8656233 ProxyCredential: System.Management.Automation.PSCredential
DEBUG: 00:00:02.8670347 Debug: True
DEBUG: 00:00:02.8683619 Proxy: http://proxy:8080/
DEBUG: 00:00:02.8699845 Scope: AllUsers
DEBUG: 00:00:02.8714744 AllowPrereleaseVersions: False
DEBUG: 00:00:02.8728025 Name: Pester
DEBUG: 00:00:02.8749958 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:02.8770521 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:02.8783457 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:02.8798970 OPTION: Type => Module
DEBUG: 00:00:02.8811825 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:02.8825294 OPTION: ProxyCredential => System.Management.Automation.PSCredential
DEBUG: 00:00:02.8838649 OPTION: Debug => True
DEBUG: 00:00:02.8852856 OPTION: Proxy => http://proxy:8080/
DEBUG: 00:00:02.8866356 OPTION: Scope => AllUsers
DEBUG: 00:00:02.8879036 OPTION: AllowPrereleaseVersions => False
DEBUG: 00:00:02.8891588 OPTION: Name => Pester
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2' and PackageManagementProvider is 'NuGet'.
DEBUG: 00:00:02.9183109 PackageProvider::FindPackage with name Pester
DEBUG: 00:00:02.9268413 Calling 'NuGet'::'FindPackage' - name='Pester', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:02.9652186 Iterating 'Pester'.
DEBUG: 00:00:02.9675696 There are '2' registered sources in 'NuGet' provider.
DEBUG: 00:00:02.9694252 Calling 'NuGetRequest'::'GetPackageById', 'Pester'.
VERBOSE: Retry downloading 'https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2' for '2' more times
VERBOSE: Retry downloading 'https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2' for '1' more times
VERBOSE: Retry downloading 'https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2' for '0' more times
WARNING: Cannot access 'https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2'. Are you missing 'Credential' parameter in the cmdlet?
DEBUG: 00:00:05.3775995 System.ArgumentException: Query Url https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2 is invalid.
   at Microsoft.PackageManagement.NuGetProvider.HttpClientPackageRepository..ctor(String queryUrl, NuGetRequest request)
   at Microsoft.PackageManagement.NuGetProvider.PackageRepositoryFactory.CreateRepository(String packageSource, NuGetRequest request)
   at Microsoft.PackageManagement.NuGetProvider.PackageSource.get_Repository()
   at Microsoft.PackageManagement.NuGetProvider.NuGetRequest.GetPackageById(PackageSource source, String name, NuGetRequest request, String requiredVersion, String minimumVersion, String m
aximumVersion, Boolean minInclusive, Boolean maxInclusive)
VERBOSE: Total package yield:'0' for the specified package 'Pester'.
DEBUG: 00:00:05.3978067 Completed iterating for 'Pester'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
DEBUG: 00:00:05.4076986 PackageProvider::FindPackage with name Pester
DEBUG: 00:00:05.4267941 Calling 'NuGet'::'FindPackage' - name='Pester', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:05.4287838 Iterating 'Pester'.
VERBOSE: Total package yield:'0' for the specified package 'Pester'.
DEBUG: 00:00:05.4327269 Completed iterating for 'Pester'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'http://on-prem:8080/nuget/' and PackageManagementProvider is 'NuGet'.
DEBUG: 00:00:05.4431985 PackageProvider::FindPackage with name Pester
DEBUG: 00:00:05.4493776 Calling 'NuGet'::'FindPackage' - name='Pester', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:05.4796371 Iterating 'Pester'.
VERBOSE: Total package yield:'0' for the specified package 'Pester'.
DEBUG: 00:00:05.4844730 Completed iterating for 'Pester'.
DEBUG: 00:00:05.4867117 PowerShell Script 'PSModule' Function 'Find-Package' returns null.
DEBUG: 00:00:05.4887791 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:05.4906182 unmatched package name='Pester'
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'Pester'. Try Get-PSRepository to see all available registered module repositories
.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.0\PSModule.psm1:2057 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

```

## Steps to Reproduce (for bugs)
0. Import-Module PowerShellGet -RequiredVersion 1.6.0
1. Register VSTS repo
2. Add PackageProvider Source to Nuget PackageProvider for that VSTS repo
3. Try install module Pester. Do not specify Credential for that VSTS repo to make skip it.

## Context
On-prem VM under the proxy

## Possible Solution
If you provide -Credential for VSTS repo it works well. Why?

## Your Environment
```
$PSVersionTable

Name                           Value                                                                                                                                                       
----                           -----                                                                                                                                                       
PSVersion                      5.1.14409.1005                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                     
BuildVersion                   10.0.14409.1005                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                             
WSManStackVersion              3.0                                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                                         
SerializationVersion           1.1.0.1

> Get-Module

ModuleType Version    Name                                ExportedCommands                                                                                                                 
---------- -------    ----                                ----------------                                                                                                                 
Manifest   1.0.0.0    ActiveDirectory                     {Add-ADComputerServiceAccount, Add-ADDomainControllerPasswordReplicationPolicy, Add-ADFineGrainedPasswordPolicySubject, Add-AD...
Script     1.0        GroupSet                            {BuildResourceCommonParameters, BuildResourceString, GroupSet}                                                                   
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                                                                              
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}                                                               
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSignature...}                                        
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                        
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}                                                  
Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                                        
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                                            
Script     1.0        ProcessSet                          {BuildResourceCommonParameters, BuildResourceString, ProcessSet}                                                                 
Manifest   1.1        PSDesiredStateConfiguration         {Invoke-DscResource, Publish-DscConfiguration, Set-DscLocalConfigurationManager, Start-DscConfiguration...}                      
Script     1.0        ServiceSet                          {BuildResourceCommonParameters, BuildResourceString, ServiceSet}                                                                 
Manifest   21.0.17199 SqlServer                           {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvailabilityGroupListenerStaticIp, Add-SqlAzureAuthenticationContext...}    
Script     1.0        WindowsFeatureSet                   {BuildResourceCommonParameters, BuildResourceString, WindowsFeatureSet}                                                          
Script     1.0        WindowsOptionalFeatureSet           {BuildResourceCommonParameters, BuildResourceString, WindowsOptionalFeatureSet}                                                  



> Get-Module -ListAvailable PowerShellGet,PackageManagement

    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                 
---------- -------    ----                                ----------------                                                                                                                 
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                                                           
Script     1.1.1.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                                                           
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                                                           
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                                                                     
Script     1.1.2.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                                                                     
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}   

> Get-PackageProvider
Name                     Version          DynamicOptions                                                                                                                                   
----                     -------          --------------                                                                                                                                   
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion, ForceX86, PackageSaveMode, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, Sk...
msi                      3.0.0.0          AdditionalArguments                                                                                                                              
msu                      3.0.0.0                                                                                                                                                           
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate          
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVersions, Filter, Tag, I...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent   

> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions                                                                                                                                   
----                     -------          --------------                                                                                                                                   
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion, ForceX86, PackageSaveMode, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, Sk...
msi                      3.0.0.0          AdditionalArguments                                                                                                                              
msu                      3.0.0.0                                                                                                                                                           
nuget                    2.8.5.208                                                                                                                                                         
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate          
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVersions, Filter, Tag, I...
PowerShellGet            1.1.2.0                                                                                                                                                           
PowerShellGet            1.0.0.1                                                                                                                                                           
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent


> Get-PackageSource
Name                             ProviderName     IsTrusted  Location                                                                                                                      
----                             ------------     ---------  --------                                                                                                                      
chocolatey                       Chocolatey       False      http://chocolatey.org/api/v2/                                                                                                 
nuget.org                        NuGet            False      https://www.nuget.org/api/v2/                                                                                                 
VSTS                             NuGet            True       https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2                                         
VSTS                             PowerShellGet    True       https://x.pkgs.visualstudio.com/_packaging/TFSOnlinePackages/nuget/v2                                         
PSGallery                        PowerShellGet    True       https://www.powershellgallery.com/api/v2/                                                                                     
OnPrem                           PowerShellGet    False      http://on-prem:8080/nuget/ 

```

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
