### ISSUE TITLE
Fail to install NuGet

### ISSUE THREAD

**Issue by Jerry4013** [PowerShell/PSResourceGet#488]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Following the docs https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.1, I tried to install the latest NuGet provider from PowerShell 7.1.4 (run as admin), but I got the error below:
```PS C:\Windows\System32> Install-PackageProvider -Name NuGet -Force
Install-PackageProvider: Unhandled Exception - Message:'The type initializer for 'Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicType' threw an exception.' Name:'TypeInitializationException' Stack Trace:'   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicType.Create(Type tInterface, OrderedDictionary`2 instanceMethods, List`2 delegateMethods, List`1 stubMethods, List`2 usedInstances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterface.CreateProxy(Type tInterface, Object[] instances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterface.DynamicCast(Type tInterface, Object[] instances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterface.DynamicCast[TInterface](Object[] instances)
   at Microsoft.PackageManagement.Internal.Utility.Plugin.DynamicInterfaceExtensions.As[TInterface](Object instance)
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletBase.get_PackageManagementHost()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletBase.SelectProviders(String[] names)
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletWithProvider.get_SelectedProviders()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageProvider.get_SelectedProviders()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletWithProvider.<get_CachedSelectedProviders>b__23_0()
   at Microsoft.PackageManagement.Internal.Utility.Extensions.DictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`1 valueFunction)
   at Microsoft.PackageManagement.Internal.Utility.Extensions.Singleton`1.GetOrAdd(Func`1 newInstance, Object primaryKey, Object[] keys)
   at Microsoft.PackageManagement.Internal.Utility.Extensions.SingletonExtensions.GetOrAdd[TResult](Object primaryKey, Func`1 newInstance, Object[] keys)
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletWithProvider.get_CachedSelectedProviders()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.CmdletWithProvider.GenerateDynamicParameters()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.AsyncCmdlet.<>c__DisplayClass83_0.<AsyncRun>b__0()'```

### Expected behavior

```console
Expected the NuGet can be installed correctly.
```

### Actual behavior

```console
error when install NuGet
```

### Environment data

```powershell
PowerShell 7.1.4
Windows 10
```

**Comment by StevenBucher98** [comment]
Thanks @Jerry4013, here are steps for a possible solution:

1. Manually download [PackageManagement ](https://www.powershellgallery.com/packages/PackageManagement/1.4.7)and [PowerShellGet](https://www.powershellgallery.com/packages/PowerShellGet/2.2.5) and
2. Extract the `.nupkg` file 
3. Look at the `$env:PSModulePath` and look at first path given
3. Copy the contents into that path
4. Make sure the name of the parent folder that you copy over is just `PackageManagement` and `PowerShellGet` respectively (sometimes the version number is include so do not include that)
5. When using PowerShell be sure to open up a fresh session.

Let us know if this works for you or if you have any issues with this!

**Comment by alerickson** [comment]
Going to close this issue, we can reopen if you're still having this issue or having trouble with workaround provided above.
