### ISSUE TITLE
*-Package -TemporaryPath appends $PWD to value

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#947]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

The path appends the current working directory with the temporary path parameter value.

### Expected behavior

```console
# works
```

### Actual behavior

```console
Install-PSResource snmp -TemporaryPath Temp: -TrustRepository
Install-PSResource: Unable to successfully install package 'SNMP': 'The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Thomas\Temp:\f2b5f446-dbbf-4d12-8565-7e016f2aea88''
```

### Error details

```console
Exception             :
    Type           : System.Management.Automation.PSInvalidOperationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Unable to successfully install package 'SNMP': 'The filename, directory name, or volume label
syntax is incorrect. : 'C:\Users\Thomas\Temp:\f2b5f446-dbbf-4d12-8565-7e016f2aea88''
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperation
    Message        : Unable to successfully install package 'SNMP': 'The filename, directory name, or volume label
syntax is incorrect. : 'C:\Users\Thomas\Temp:\f2b5f446-dbbf-4d12-8565-7e016f2aea88''
    InnerException :
        Type       : System.IO.IOException
        TargetSite :
            Name          : CreateDirectory
            DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Message    : The filename, directory name, or volume label syntax is incorrect. :
'C:\Users\Thomas\Temp:\f2b5f446-dbbf-4d12-8565-7e016f2aea88'
        Source     : System.Private.CoreLib
        HResult    : -2147024773
        StackTrace :
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallHelper.InstallPackage(List`1 pkgsToInstall, String repoName,
String repoUri, PSCredentialInfo repoCredentialInfo, PSCredential credential, Boolean isLocalRepo, ScopeType scope)
    HResult        : -2146233079
TargetObject          : Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource
CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…s.InstallPSResource:InstallPSResource)
[Install-PSResource], PSInvalidOperationException
FullyQualifiedErrorId : InstallPackageFailed,Microsoft.PowerShell.PowerShellGet.Cmdlets.InstallPSResource
InvocationInfo        :
    MyCommand        : Install-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Install-PSResource snmp -TemporaryPath Temp: -TrustRepository
    PositionMessage  : At line:1 char:1
                       + Install-PSResource snmp -TemporaryPath Temp: -TrustRepository
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Install-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
Name          Version
----          -------
PowerShellGet 3.0.19

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
I am not reproducing this with beta20, this may be resolved

**Comment by ThomasNieto** [comment]
This is not resolved on beta21.
