### ISSUE TITLE
[PowerShellGet v3] `Find-PSResource` throws NullRef if it couldn't find anything

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PSResourceGet#95]
### Repro

```pwsh
Find-PSResource Az.Cosmos
```

### Expected

Some friendly error that says "couldn't find anything" or no output at all

### Actual

```
Find-PSResource: Object reference not set to an instance of an object.
```

### Extra info

Looks like it's in the ProcessRecord somewhere:

```
PS > $Error[0].Exception.StackTrace
   at Microsoft.PowerShell.PowerShellGet.Cmdlets.FindPSResource.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by alerickson** [comment]
Addressed with release of 3.0.0-beta2
